name: Agendador de amor

on:
  schedule:
      - cron: '0 */2 * * *'

  workflow_dispatch:
  
  
jobs:
  executar-amor:
    runs-on: ubuntu-latest
    steps:
    - name: Checar código
      uses: actions/checkout@v2

    - name: Instalando streamlink e selenium
      run: |
          pip install --user --upgrade streamlink
          pip install --user --upgrade selenium
          pip install yt-dlp
          pip install pytube
          pip install youtube-dl
          pip install requests
          pip install beautifulsoup4
          pip install fastapi
          pip install uvicorn
          pip install schedule
          
      
    - name: Executar script
      run: python amor.py
      
    - name: Configurar Git
      run: |
        git config --global user.name "seu nome de usuário"
        git config --global user.email "seu endereço de e-mail"

    - name: Adicionar alterações ao Git
      run: |
        git add .

    - name: Criar commit
      run: |
        git commit -m "mensagem do commit"

    - name: Fazer push no repositório
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
