name: Agendador de amor

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  executar-amor:
    runs-on: windows-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
      
      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      
      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install streamlink
          pip install selenium
          pip install yt-dlp
          pip install pytube
          pip install beautifulsoup4
      
      - name: Executar script
        run: python amor.py
      
      - name: Verificar credenciais do GitHub
        run: |
          git config user.name && git config user.email
      - name: Fazer commit e push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Atualizando informações de amor
          commit_options: '--no-verify'
          commit_user_name: ${{ secrets.USERNAME }}
          commit_user_email: ${{ secrets.EMAIL }}
