name: Agendador de amor

on:
  schedule:
    - cron: '0 */2 * * *'

  workflow_dispatch:
  
  
jobs:
  executar-amor:
    runs-on: ubuntu-latest
    steps:
    - name: Checar código
      uses: actions/checkout@v2
    - name: Instalando streamlink e selenium
      run: |
          pip install --user --upgrade streamlink
          pip install --user --upgrade selenium
          pip install yt-dlp
          pip install pytube
          pip install youtube-dl
          pip install requests
          pip install beautifulsoup4
          pip install fastapi
          pip install uvicorn
          pip install schedule
          
    - name: Executar script
      run: python amor.py
      
    - name: Fazer push do arquivo YAML
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add separados.yml
          git commit -m "Atualizar separados.yml"
          git push origin HEAD:main
          
    - name: Criar arquivo YAML
      run: touch separados.yml


    - name: Fazer push do arquivo YAML
      env:
        FILENAME: 'separados.yml'
        COMMIT_MESSAGE: 'Atualizar separados.yml'
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add $FILENAME
        git commit -m "$COMMIT_MESSAGE"
        git push
